version: '3.2'
services:
  app:
    profiles: ["build"]
    build:
      dockerfile: ./Dockerfile
    volumes:
        - ./downloads:/app/downloads
        - ./subscriptions.json:/app/subscriptions.json
